language: en
pipeline:
- name: ConveRTTokenizer
- name: ConveRTFeaturizer
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
#- name: CountVectorsFeaturizer
#  OOV_token: oov
#  token_pattern: (?u)\b\w+\b
#- name: CountVectorsFeaturizer
#  analyzer: char_wb
#  min_ngram: 1
#  max_ngram: 4
- name: CRFEntityExtractor
- name: DIETClassifier
  epochs: 50
  ranking_length: 5
  hidden_layers_sizes:
    text: [256,128]
    label: []
    dense_dimension:
      text: 256
      label: 20
    number_of_transformer_layers: 0
    entity_recognition: False
    BILOU_flag: False
- name: DucklingHTTPExtractor
  url: http://localhost:8000
  dimensions:
  - email
  - number
  - amount-of-money
- name: EntitySynonymMapper
- name: ResponseSelector
  retrieval_intent: out_of_scope
  scale_loss: false
- name: ResponseSelector
  retrieval_intent: faq
  scale_loss: false
- name: ResponseSelector
  retrieval_intent: chitchat
  scale_loss: false
policies:
- name: TEDPolicy
  max_history: 10
  epochs: 20
  batch_size:
  - 32
  - 64
- max_history: 6
  name: AugmentedMemoizationPolicy
- core_threshold: 0.3
  name: TwoStageFallbackPolicy
  nlu_threshold: 0.8
  deny_suggestion_intent_name: "trigger_rephrase"
- name: FormPolicy
- name: MappingPolicy
