language: en
pipeline:
- name: tokenizer_whitespace
  intent_split_symbol: '_'
- name: CRFEntityExtractor
- name: intent_featurizer_count_vectors
  use_shared_vocab: true
- name: EmbeddingIntentClassifier
  epochs: 40
  evaluate_every_num_epochs: 5
  evaluate_on_num_examples: 256
  hidden_layers_sizes_a:
    - 128
    - 64
  hidden_layers_sizes_b:
    - 128
    - 64
  droprate: 0.2
  stratified_batch: False
  batch_size: [64, 128]
  share_embedding: true
  embed_dim: 20
  similarity_type: cosine
  loss_type: margin
  intent_tokenization_flag: true
  iou_threshold: 0.66
- name: ResponseSelector
  epochs: 40
  evaluate_every_num_epochs: 5
  evaluate_on_num_examples: 256
  hidden_layers_sizes_a:
    - 128
    - 64
  hidden_layers_sizes_b:
    - 128
    - 64
  batch_size: [64,128]
  droprate: 0.2
  stratified_batch: True
  share_embedding: true
  embed_dim: 20
  similarity_type: cosine
  loss_type: margin
  intent_tokenization_flag: true
  iou_threshold: 0.66
- name: DucklingHTTPExtractor
  url: http://localhost:8000
  dimensions:
  - email
  - number
  - amount-of-money
- name: EntitySynonymMapper

policies:
- epochs: 50
  max_history: 6
  name: KerasPolicy
- max_history: 6
  name: AugmentedMemoizationPolicy
- core_threshold: 0.3
  name: TwoStageFallbackPolicy
  nlu_threshold: 0.8
- name: FormPolicy
- name: MappingPolicy
