language: en
pipeline:
  - name: "tokenizer_whitespace"
  - name: "ner_crf"
  - name: "ner_synonyms"
  - name: "innatis.classifiers.BertIntentClassifier"
    "batch_size": 64
    "epochs": 100
    "learning_rate": 2e-5
    "max_seq_length": 128
