language: en

#pipeline: supervised_embeddings
pipeline:
#- name: HFTransformersNLP
#- name: SpacyNLP
- name: WhitespaceTokenizer
#  intent_tokenization_flag: True
#- name: SpacyTokenizer
#  intent_tokenization_flag: True
#- name: ConveRTTokenizer
#  intent_tokenization_flag: True
#- name: LanguageModelTokenizer
#- name: SpacyFeaturizer
#- name: ConveRTFeaturizer
#- name: LanguageModelFeaturizer
- name: CountVectorsFeaturizer
  OOV_token: oov
  token_pattern: (?u)\b\w+\b
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 5
#- name: CRFEntityExtractor
#  epochs: 2
- name: EmbeddingIntentClassifier
  epochs: 50
#- name: DIETClassifier
#  epochs: 100
#  hidden_layers_sizes:
#    text: [256, 128]
#    label: []
#  transformer_size: 32
#  batch_size: 64
#  scale_loss: False
#  unidirectional_encoder: True
#  use_masked_language_model: True
#  entity_recognition: False
#  use_sparse_input_dropout: True
#  number_of_transformer_layers: 2
##  var_layers: ["cls", "crf", "mask"]
#  evaluate_on_number_of_examples: 100
#  evaluate_every_number_of_epochs: 3
##  BILOU_flag: True
##  droprate: 0.2
##  batch_strategy: sequence
##- name: DucklingHTTPExtractor
##  url: http://localhost:8000
##  dimensions:
##  - email
##  - number
##  - amount-of-money
##- name: EntitySynonymMapper
#- name: ResponseSelector
#  epochs: 2