language: en
pipeline:
- name: "tokenizer_whitespace"
- name: "intent_featurizer_count_vectors"
  OOV_token: oov
  token_pattern: (?u)\b\w+\b
  min_df: 0.0005037276865894005
  max_df: 0.28739707372807394
  max_ngram: 3
- name: "intent_classifier_tensorflow_embedding"
  epochs: 40
  batch_size: 160
  embed_dim: 280
  C2: 0.0032376715432725607
  C_emb: 0.0007105954433443403
  num_hidden_layers_a: 0
  hidden_layer_size_a: 80
  num_hidden_layers_b: 4
  hidden_layer_size_b: 200
