policies:
  - name: KerasPolicy
    epochs: 200
    batch_size: 8
    featurizer:
      - name: FullDialogueTrackerFeaturizer
        state_featurizer:
        - name: BinarySingleStateFeaturizer
#    max_history: 6
#  - name: MemoizationPolicy
#    max_history: 6
#  - name: FallbackPolicy
#    nlu_threshold: 0.8
#    core_threshold: 0.3
  - name: FormPolicy
