policies:
  - name: EmbeddingPolicy
    max_history: 6
    transformer: true
    epochs: 200
    batch_size: [32, 64]
    attn_shift_range: 5
    num_neg: 20
    similarity_type: 'inner'
    scale_loss_by_action_counts: true
#    C2: 0.0
    evaluate_every_num_epochs: 10
    evaluate_on_num_examples: 10
  - name: FormPolicy