  
name: Build and Deploy
on: [push]

jobs:
  build-images:
    name: Build and Push Images
    runs-on: ubuntu-latest

    steps:
    - name: Code Formatting Tests
      working-directory: ./
      run: |
        make lint