  
name: Build and Deploy
on: [push]

jobs:
  build-images:
    name: Build and Push Images
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Code Formatting Tests
      working-directory: ${{ github.workspace }}
      run: |
        make lint