  
name: Build and Deploy
on: [push]

jobs:
  build-images:
    name: Build and Push Images
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
    - name: Code Formatting Tests
      working-directory: ${{ github.workspace }}
      run: |
        make lint
    - name: Type Checking
      working-directory: ${{ github.workspace }}
      run: |
        make types
    - name: Test Training Stories
      working-directory: ${{ github.workspace }}
      run: |
        rasa train core --config augmentedmemo-only.yml --augmentation 0 --quiet
        rasa test core --fail-on-prediction-errors --quiet
